python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_51.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_51.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_51.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_51.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_51.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_51.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_51.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2W1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2W1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2W1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2W1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2W1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2W1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2W1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C19.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C19.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C19.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C19.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C19.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C19.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C19.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2B6.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2B6.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2B6.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2B6.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2B6.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2B6.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2B6.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Putative_cytochrome_P450_2D7.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Putative_cytochrome_P450_2D7.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Putative_cytochrome_P450_2D7.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Putative_cytochrome_P450_2D7.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Putative_cytochrome_P450_2D7.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Putative_cytochrome_P450_2D7.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Putative_cytochrome_P450_2D7.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C18.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C18.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C18.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C18.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C18.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C18.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C18.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_family_4_subfamily_X_polypeptide_1_isoform_CRA_c.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_family_4_subfamily_X_polypeptide_1_isoform_CRA_c.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_family_4_subfamily_X_polypeptide_1_isoform_CRA_c.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_family_4_subfamily_X_polypeptide_1_isoform_CRA_c.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_family_4_subfamily_X_polypeptide_1_isoform_CRA_c.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_family_4_subfamily_X_polypeptide_1_isoform_CRA_c.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_family_4_subfamily_X_polypeptide_1_isoform_CRA_c.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c_oxidase_subunit_1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c_oxidase_subunit_1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c_oxidase_subunit_1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c_oxidase_subunit_1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c_oxidase_subunit_1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c_oxidase_subunit_1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c_oxidase_subunit_1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_26A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_26A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_26A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_26A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_26A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_26A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_26A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1B1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1B1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1B1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1B1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1B1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1B1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1B1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_24A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_24A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_24A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_24A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_24A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_24A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_24A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c_oxidase_subunit_2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c_oxidase_subunit_2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c_oxidase_subunit_2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c_oxidase_subunit_2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c_oxidase_subunit_2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c_oxidase_subunit_2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c_oxidase_subunit_2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_19A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_19A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_19A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_19A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_19A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_19A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_19A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_11B1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_11B1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_11B1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_11B1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_11B1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_11B1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_11B1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2E1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2E1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2E1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2E1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2E1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2E1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2E1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_21.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_21.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_21.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_21.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_21.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_21.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_21.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c1_heme_protein_mitochondrial.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c1_heme_protein_mitochondrial.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c1_heme_protein_mitochondrial.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c1_heme_protein_mitochondrial.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c1_heme_protein_mitochondrial.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c1_heme_protein_mitochondrial.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c1_heme_protein_mitochondrial.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_11B2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_11B2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_11B2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_11B2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_11B2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_11B2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_11B2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2D6.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2D6.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2D6.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2D6.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2D6.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2D6.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2D6.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A7.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A7.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A7.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A7.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A7.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A7.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A7.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_b_c1_complex_subunit_7.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_b_c1_complex_subunit_7.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_b_c1_complex_subunit_7.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_b_c1_complex_subunit_7.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_b_c1_complex_subunit_7.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_b_c1_complex_subunit_7.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_b_c1_complex_subunit_7.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A4.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A4.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A4.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A4.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A4.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A4.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A4.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_11A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_11A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_11A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_11A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_11A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_11A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_11A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2J2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2J2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2J2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2J2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2J2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2J2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2J2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A5.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A5.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A5.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A5.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A5.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A5.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A5.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/NADPH_cytochrome_P450_reductase.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/NADPH_cytochrome_P450_reductase.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/NADPH_cytochrome_P450_reductase.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/NADPH_cytochrome_P450_reductase.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/NADPH_cytochrome_P450_reductase.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/NADPH_cytochrome_P450_reductase.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/NADPH_cytochrome_P450_reductase.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_4A11.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_4A11.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_4A11.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_4A11.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_4A11.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_4A11.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_4A11.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1A2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1A2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1A2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1A2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1A2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1A2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1A2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_4F2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_4F2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_4F2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_4F2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_4F2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_4F2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_4F2.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_b_245_heavy_chain.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_b_245_heavy_chain.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_b_245_heavy_chain.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_b_245_heavy_chain.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_b_245_heavy_chain.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_b_245_heavy_chain.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_b_245_heavy_chain.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_17A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_17A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_17A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_17A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_17A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_17A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_17A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_b5.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_b5.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_b5.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_b5.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_b5.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_b5.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_b5.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_26B1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_26B1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_26B1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_26B1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_26B1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_26B1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_26B1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1A.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1A.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1A.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1A.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1A.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1A.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1A.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_1A1.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_4F12.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_4F12.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_4F12.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_4F12.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_4F12.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_4F12.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_4F12.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A43.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A43.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A43.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A43.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A43.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A43.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A43.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2A6.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2A6.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2A6.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2A6.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2A6.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2A6.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2A6.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A4_3A5.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A4_3A5.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A4_3A5.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A4_3A5.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A4_3A5.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A4_3A5.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_3A4_3A5.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Apoptotic_protease_activating_factor_1_Caspase_3_Caspase_9_Cytochrome_c.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Apoptotic_protease_activating_factor_1_Caspase_3_Caspase_9_Cytochrome_c.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Apoptotic_protease_activating_factor_1_Caspase_3_Caspase_9_Cytochrome_c.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Apoptotic_protease_activating_factor_1_Caspase_3_Caspase_9_Cytochrome_c.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Apoptotic_protease_activating_factor_1_Caspase_3_Caspase_9_Cytochrome_c.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Apoptotic_protease_activating_factor_1_Caspase_3_Caspase_9_Cytochrome_c.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Apoptotic_protease_activating_factor_1_Caspase_3_Caspase_9_Cytochrome_c.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_c.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/NADH_cytochrome_b5_reductase.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/NADH_cytochrome_b5_reductase.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/NADH_cytochrome_b5_reductase.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/NADH_cytochrome_b5_reductase.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/NADH_cytochrome_b5_reductase.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/NADH_cytochrome_b5_reductase.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/NADH_cytochrome_b5_reductase.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Ubiquinol_cytochrome_C_reductase_complex_7.2_kDa_protein.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Ubiquinol_cytochrome_C_reductase_complex_7.2_kDa_protein.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Ubiquinol_cytochrome_C_reductase_complex_7.2_kDa_protein.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Ubiquinol_cytochrome_C_reductase_complex_7.2_kDa_protein.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Ubiquinol_cytochrome_C_reductase_complex_7.2_kDa_protein.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Ubiquinol_cytochrome_C_reductase_complex_7.2_kDa_protein.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Ubiquinol_cytochrome_C_reductase_complex_7.2_kDa_protein.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2A13.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2A13.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2A13.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2A13.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2A13.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2A13.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2A13.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C9.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C9.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C9.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C9.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C9.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C9.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C9.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py morgan_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C8.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py maccs_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C8.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py avalon_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C8.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py rdk_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C8.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py topological_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C8.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp2_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C8.csv ../dataset/cyt_homo_data/numpy_files
python3 generate_fp_v2.py ecfp6_fp ../dataset/cyt_homo_data/filtered/relation_D/Cytochrome_P450_2C8.csv ../dataset/cyt_homo_data/numpy_files
