python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/1A1_ind_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/1A1_ind_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/1A1_ind_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/1A1_inh_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/1A1_inh_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/1A1_inh_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/1A1_sub_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/1A1_sub_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/1A1_sub_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/1A2_ind_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/1A2_ind_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/1A2_ind_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/1A2_inh_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/1A2_inh_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/1A2_inh_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/1A2_sub_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/1A2_sub_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/1A2_sub_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C19_ind_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C19_ind_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C19_ind_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C19_inh_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C19_inh_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C19_inh_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C19_sub_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C19_sub_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C19_sub_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C8_ind_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C8_ind_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C8_ind_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C8_inh_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C8_inh_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C8_inh_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C8_sub_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C8_sub_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C8_sub_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C9_ind_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C9_ind_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C9_ind_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C9_inh_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C9_inh_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C9_inh_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C9_sub_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C9_sub_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2C9_sub_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2D6_inh_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2D6_inh_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2D6_inh_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2D6_sub_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2D6_sub_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2D6_sub_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2E1_ind_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2E1_ind_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2E1_ind_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2E1_inh_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2E1_inh_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2E1_inh_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2E1_sub_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2E1_sub_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/2E1_sub_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/3A4_ind_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/3A4_ind_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/3A4_ind_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/3A4_inh_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/3A4_inh_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/3A4_inh_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/3A4_sub_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/3A4_sub_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/3A4_sub_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/3A5_ind_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/3A5_ind_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/3A5_ind_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/3A5_inh_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/3A5_inh_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/3A5_inh_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/3A5_sub_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/3A5_sub_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/3A5_sub_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/GST_ind_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/GST_ind_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/GST_ind_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/GST_inh_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/GST_inh_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/GST_inh_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/GST_sub_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/GST_sub_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/GST_sub_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/MET_ind_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/MET_ind_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/MET_ind_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/MET_inh_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/MET_inh_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/MET_inh_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/MET_sub_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/MET_sub_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/MET_sub_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/NAT_ind_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/NAT_ind_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/NAT_ind_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/NAT_inh_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/NAT_inh_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/NAT_inh_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/NAT_sub_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/NAT_sub_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/NAT_sub_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/SUL_ind_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/SUL_ind_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/SUL_ind_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/SUL_inh_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/SUL_inh_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/SUL_inh_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/SUL_sub_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/SUL_sub_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/SUL_sub_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/UGT_ind_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/UGT_ind_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/UGT_ind_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/UGT_inh_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/UGT_inh_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/UGT_inh_te.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/UGT_sub_tr.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/UGT_sub_va.csv ../dataset/combined_fp_numpy_files
python3 generate_fp_v7.py rdkDes_lecfp6_laval_hashap ../dataset/csv_files/splitted_csv_files/UGT_sub_te.csv ../dataset/combined_fp_numpy_files
