python3 generate_fp_v8.py rdk7 ../dataset/csv_files/2D6_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py lfcfp6 ../dataset/csv_files/2D6_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py fcfp6 ../dataset/csv_files/2D6_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py ecfp0 ../dataset/csv_files/2D6_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py fcfp4 ../dataset/csv_files/2D6_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py rdk6 ../dataset/csv_files/2D6_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py avalon ../dataset/csv_files/2D6_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py fcfp2 ../dataset/csv_files/2D6_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py ecfp2 ../dataset/csv_files/2D6_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py maccs ../dataset/csv_files/2D6_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py laval ../dataset/csv_files/2D6_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py ecfp6 ../dataset/csv_files/2D6_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py ecfp4 ../dataset/csv_files/2D6_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py lfcfp4 ../dataset/csv_files/2D6_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py hashtt ../dataset/csv_files/2D6_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py lecfp6 ../dataset/csv_files/2D6_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py lecfp4 ../dataset/csv_files/2D6_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py hashap ../dataset/csv_files/2D6_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py rdk5 ../dataset/csv_files/2D6_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py rdkDes ../dataset/csv_files/2D6_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py ecfp6_rdkDes_avalon_hashap ../dataset/csv_files/2D6_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py rdk7 ../dataset/csv_files/2C9_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py lfcfp6 ../dataset/csv_files/2C9_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py fcfp6 ../dataset/csv_files/2C9_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py ecfp0 ../dataset/csv_files/2C9_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py fcfp4 ../dataset/csv_files/2C9_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py rdk6 ../dataset/csv_files/2C9_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py avalon ../dataset/csv_files/2C9_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py fcfp2 ../dataset/csv_files/2C9_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py ecfp2 ../dataset/csv_files/2C9_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py maccs ../dataset/csv_files/2C9_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py laval ../dataset/csv_files/2C9_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py ecfp6 ../dataset/csv_files/2C9_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py ecfp4 ../dataset/csv_files/2C9_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py lfcfp4 ../dataset/csv_files/2C9_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py hashtt ../dataset/csv_files/2C9_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py lecfp6 ../dataset/csv_files/2C9_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py lecfp4 ../dataset/csv_files/2C9_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py hashap ../dataset/csv_files/2C9_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py rdk5 ../dataset/csv_files/2C9_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py rdkDes ../dataset/csv_files/2C9_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py ecfp6_rdkDes_avalon_hashap ../dataset/csv_files/2C9_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py rdk7 ../dataset/csv_files/2C19_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py lfcfp6 ../dataset/csv_files/2C19_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py fcfp6 ../dataset/csv_files/2C19_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py ecfp0 ../dataset/csv_files/2C19_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py fcfp4 ../dataset/csv_files/2C19_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py rdk6 ../dataset/csv_files/2C19_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py avalon ../dataset/csv_files/2C19_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py fcfp2 ../dataset/csv_files/2C19_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py ecfp2 ../dataset/csv_files/2C19_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py maccs ../dataset/csv_files/2C19_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py laval ../dataset/csv_files/2C19_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py ecfp6 ../dataset/csv_files/2C19_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py ecfp4 ../dataset/csv_files/2C19_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py lfcfp4 ../dataset/csv_files/2C19_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py hashtt ../dataset/csv_files/2C19_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py lecfp6 ../dataset/csv_files/2C19_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py lecfp4 ../dataset/csv_files/2C19_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py hashap ../dataset/csv_files/2C19_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py rdk5 ../dataset/csv_files/2C19_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py rdkDes ../dataset/csv_files/2C19_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py ecfp6_rdkDes_avalon_hashap ../dataset/csv_files/2C19_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py rdk7 ../dataset/csv_files/1A2_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py lfcfp6 ../dataset/csv_files/1A2_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py fcfp6 ../dataset/csv_files/1A2_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py ecfp0 ../dataset/csv_files/1A2_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py fcfp4 ../dataset/csv_files/1A2_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py rdk6 ../dataset/csv_files/1A2_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py avalon ../dataset/csv_files/1A2_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py fcfp2 ../dataset/csv_files/1A2_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py ecfp2 ../dataset/csv_files/1A2_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py maccs ../dataset/csv_files/1A2_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py laval ../dataset/csv_files/1A2_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py ecfp6 ../dataset/csv_files/1A2_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py ecfp4 ../dataset/csv_files/1A2_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py lfcfp4 ../dataset/csv_files/1A2_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py hashtt ../dataset/csv_files/1A2_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py lecfp6 ../dataset/csv_files/1A2_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py lecfp4 ../dataset/csv_files/1A2_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py hashap ../dataset/csv_files/1A2_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py rdk5 ../dataset/csv_files/1A2_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py rdkDes ../dataset/csv_files/1A2_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py ecfp6_rdkDes_avalon_hashap ../dataset/csv_files/1A2_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py rdk7 ../dataset/csv_files/3A4_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py lfcfp6 ../dataset/csv_files/3A4_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py fcfp6 ../dataset/csv_files/3A4_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py ecfp0 ../dataset/csv_files/3A4_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py fcfp4 ../dataset/csv_files/3A4_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py rdk6 ../dataset/csv_files/3A4_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py avalon ../dataset/csv_files/3A4_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py fcfp2 ../dataset/csv_files/3A4_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py ecfp2 ../dataset/csv_files/3A4_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py maccs ../dataset/csv_files/3A4_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py laval ../dataset/csv_files/3A4_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py ecfp6 ../dataset/csv_files/3A4_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py ecfp4 ../dataset/csv_files/3A4_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py lfcfp4 ../dataset/csv_files/3A4_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py hashtt ../dataset/csv_files/3A4_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py lecfp6 ../dataset/csv_files/3A4_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py lecfp4 ../dataset/csv_files/3A4_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py hashap ../dataset/csv_files/3A4_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py rdk5 ../dataset/csv_files/3A4_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py rdkDes ../dataset/csv_files/3A4_inh.csv ../dataset/numpy_files
python3 generate_fp_v8.py ecfp6_rdkDes_avalon_hashap ../dataset/csv_files/3A4_inh.csv ../dataset/numpy_files
