python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/ecfp2-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/ecfp2-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/ecfp2-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/ecfp2-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/ecfp2-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/ecfp2-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/ecfp2-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/ecfp2-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/ecfp2-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/ecfp2-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/maccs-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/maccs-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/maccs-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/maccs-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/maccs-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/maccs-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/maccs-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/maccs-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/maccs-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/maccs-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/laval-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/laval-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/laval-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/laval-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/laval-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/laval-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/laval-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/laval-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/laval-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/laval-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/ecfp6-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/ecfp6-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/ecfp6-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/ecfp6-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/ecfp6-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/ecfp6-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/ecfp6-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/ecfp6-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/ecfp6-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/ecfp6-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/ecfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/ecfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/ecfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/ecfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/ecfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/ecfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/ecfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/ecfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/ecfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/ecfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/lfcfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/lfcfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/lfcfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/lfcfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/lfcfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/lfcfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/lfcfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/lfcfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/lfcfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/lfcfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/hashtt-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/hashtt-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/hashtt-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/hashtt-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/hashtt-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/hashtt-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/hashtt-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/hashtt-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/hashtt-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/hashtt-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/lecfp6-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/lecfp6-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/lecfp6-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/lecfp6-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/lecfp6-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/lecfp6-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/lecfp6-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/lecfp6-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/lecfp6-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/lecfp6-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/lecfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/lecfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/lecfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/lecfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/lecfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/lecfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/lecfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/lecfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/lecfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/lecfp4-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/hashap-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/hashap-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/hashap-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/hashap-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/hashap-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/hashap-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/hashap-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/hashap-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/hashap-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/hashap-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/rdk5-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/rdk5-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/rdk5-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/rdk5-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/rdk5-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/rdk5-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/rdk5-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/rdk5-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/rdk5-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/rdk5-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/rdkDes-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/rdkDes-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/rdkDes-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/rdkDes-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/rdkDes-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/rdkDes-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/rdkDes-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/rdkDes-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/rdkDes-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/rdkDes-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2C9_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/rdk7-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/rdk7-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/rdk7-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/rdk7-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/rdk7-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/rdk7-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/rdk7-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/rdk7-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/rdk7-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/rdk7-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/lfcfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/lfcfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/lfcfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/lfcfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/lfcfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/lfcfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/lfcfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/lfcfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/lfcfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/lfcfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/fcfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/fcfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/fcfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/fcfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/fcfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/fcfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/fcfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/fcfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/fcfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/fcfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/ecfp0-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/ecfp0-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/ecfp0-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/ecfp0-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/ecfp0-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/ecfp0-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/ecfp0-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/ecfp0-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/ecfp0-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/ecfp0-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/fcfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/fcfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/fcfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/fcfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/fcfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/fcfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/fcfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/fcfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/fcfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/fcfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/rdk6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/rdk6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/rdk6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/rdk6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/rdk6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/rdk6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/rdk6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/rdk6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/rdk6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/rdk6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/avalon-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/avalon-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/avalon-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/avalon-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/avalon-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/avalon-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/avalon-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/avalon-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/avalon-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/avalon-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/fcfp2-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/fcfp2-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/fcfp2-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/fcfp2-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/fcfp2-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/fcfp2-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/fcfp2-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/fcfp2-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/fcfp2-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/fcfp2-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/ecfp2-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/ecfp2-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/ecfp2-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/ecfp2-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/ecfp2-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/ecfp2-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/ecfp2-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/ecfp2-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/ecfp2-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/ecfp2-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/maccs-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/maccs-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/maccs-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/maccs-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/maccs-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/maccs-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/maccs-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/maccs-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/maccs-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/maccs-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/laval-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/laval-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/laval-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/laval-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/laval-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/laval-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/laval-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/laval-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/laval-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/laval-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/ecfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/ecfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/ecfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/ecfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/ecfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/ecfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/ecfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/ecfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/ecfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/ecfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/ecfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/ecfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/ecfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/ecfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/ecfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/ecfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/ecfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/ecfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/ecfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/ecfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/lfcfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/lfcfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/lfcfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/lfcfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/lfcfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/lfcfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/lfcfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/lfcfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/lfcfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/lfcfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/hashtt-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/hashtt-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/hashtt-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/hashtt-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/hashtt-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/hashtt-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/hashtt-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/hashtt-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/hashtt-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/hashtt-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/lecfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/lecfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/lecfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/lecfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/lecfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/lecfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/lecfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/lecfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/lecfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/lecfp6-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/lecfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/lecfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/lecfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/lecfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/lecfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/lecfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/lecfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/lecfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/lecfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/lecfp4-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/hashap-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/hashap-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/hashap-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/hashap-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/hashap-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/hashap-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/hashap-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/hashap-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/hashap-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/hashap-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/rdk5-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/rdk5-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/rdk5-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/rdk5-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/rdk5-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/rdk5-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/rdk5-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/rdk5-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/rdk5-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/rdk5-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/rdkDes-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/rdkDes-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/rdkDes-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/rdkDes-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/rdkDes-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/rdkDes-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/rdkDes-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/rdkDes-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/rdkDes-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/rdkDes-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2D6_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/rdk7-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/rdk7-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/rdk7-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/rdk7-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/rdk7-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/rdk7-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/rdk7-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/rdk7-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/rdk7-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/rdk7-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/lfcfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/lfcfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/lfcfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/lfcfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/lfcfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/lfcfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/lfcfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/lfcfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/lfcfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/lfcfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/fcfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/fcfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/fcfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/fcfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/fcfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/fcfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/fcfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/fcfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/fcfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/fcfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/ecfp0-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/ecfp0-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/ecfp0-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/ecfp0-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/ecfp0-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/ecfp0-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/ecfp0-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/ecfp0-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/ecfp0-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/ecfp0-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/fcfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/fcfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/fcfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/fcfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/fcfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/fcfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/fcfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/fcfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/fcfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/fcfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/rdk6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/rdk6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/rdk6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/rdk6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/rdk6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/rdk6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/rdk6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/rdk6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/rdk6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/rdk6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/avalon-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/avalon-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/avalon-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/avalon-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/avalon-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/avalon-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/avalon-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/avalon-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/avalon-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/avalon-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/fcfp2-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/fcfp2-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/fcfp2-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/fcfp2-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/fcfp2-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/fcfp2-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/fcfp2-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/fcfp2-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/fcfp2-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/fcfp2-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/ecfp2-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/ecfp2-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/ecfp2-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/ecfp2-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/ecfp2-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/ecfp2-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/ecfp2-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/ecfp2-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/ecfp2-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/ecfp2-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/maccs-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/maccs-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/maccs-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/maccs-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/maccs-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/maccs-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/maccs-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/maccs-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/maccs-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/maccs-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/laval-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/laval-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/laval-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/laval-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/laval-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/laval-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/laval-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/laval-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/laval-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/laval-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/ecfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/ecfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/ecfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/ecfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/ecfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/ecfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/ecfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/ecfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/ecfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/ecfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/ecfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/ecfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/ecfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/ecfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/ecfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/ecfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/ecfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/ecfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/ecfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/ecfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/lfcfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/lfcfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/lfcfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/lfcfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/lfcfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/lfcfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/lfcfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/lfcfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/lfcfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/lfcfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/hashtt-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/hashtt-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/hashtt-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/hashtt-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/hashtt-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/hashtt-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/hashtt-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/hashtt-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/hashtt-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/hashtt-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/lecfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/lecfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/lecfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/lecfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/lecfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/lecfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/lecfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/lecfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/lecfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/lecfp6-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/lecfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/lecfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/lecfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/lecfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/lecfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/lecfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/lecfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/lecfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/lecfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/lecfp4-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/hashap-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/hashap-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/hashap-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/hashap-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/hashap-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/hashap-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/hashap-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/hashap-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/hashap-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/hashap-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/rdk5-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/rdk5-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/rdk5-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/rdk5-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/rdk5-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/rdk5-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/rdk5-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/rdk5-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/rdk5-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/rdk5-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/rdkDes-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/rdkDes-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/rdkDes-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/rdkDes-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/rdkDes-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/rdkDes-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/rdkDes-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/rdkDes-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/rdkDes-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/rdkDes-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-1A2_inh.npy ../results_2 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-1A2_inh.npy ../results_2 0.0 0.20 default
