python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/rdk7-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/rdk7-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/rdk7-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/rdk7-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/rdk7-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/rdk7-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/rdk7-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/rdk7-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/rdk7-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/rdk7-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/lfcfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/lfcfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/lfcfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/lfcfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/lfcfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/lfcfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/lfcfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/lfcfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/lfcfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/lfcfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/fcfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/fcfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/fcfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/fcfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/fcfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/fcfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/fcfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/fcfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/fcfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/fcfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/ecfp0-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/ecfp0-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/ecfp0-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/ecfp0-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/ecfp0-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/ecfp0-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/ecfp0-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/ecfp0-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/ecfp0-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/ecfp0-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/fcfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/fcfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/fcfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/fcfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/fcfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/fcfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/fcfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/fcfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/fcfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/fcfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/rdk6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/rdk6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/rdk6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/rdk6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/rdk6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/rdk6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/rdk6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/rdk6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/rdk6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/rdk6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/avalon-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/avalon-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/avalon-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/avalon-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/avalon-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/avalon-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/avalon-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/avalon-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/avalon-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/avalon-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/fcfp2-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/fcfp2-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/fcfp2-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/fcfp2-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/fcfp2-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/fcfp2-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/fcfp2-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/fcfp2-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/fcfp2-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/fcfp2-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/ecfp2-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/ecfp2-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/ecfp2-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/ecfp2-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/ecfp2-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/ecfp2-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/ecfp2-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/ecfp2-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/ecfp2-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/ecfp2-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/maccs-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/maccs-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/maccs-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/maccs-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/maccs-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/maccs-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/maccs-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/maccs-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/maccs-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/maccs-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/laval-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/laval-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/laval-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/laval-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/laval-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/laval-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/laval-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/laval-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/laval-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/laval-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/ecfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/ecfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/ecfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/ecfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/ecfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/ecfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/ecfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/ecfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/ecfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/ecfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/ecfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/ecfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/ecfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/ecfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/ecfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/ecfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/ecfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/ecfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/ecfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/ecfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/lfcfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/lfcfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/lfcfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/lfcfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/lfcfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/lfcfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/lfcfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/lfcfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/lfcfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/lfcfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/hashtt-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/hashtt-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/hashtt-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/hashtt-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/hashtt-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/hashtt-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/hashtt-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/hashtt-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/hashtt-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/hashtt-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/lecfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/lecfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/lecfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/lecfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/lecfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/lecfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/lecfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/lecfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/lecfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/lecfp6-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/lecfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/lecfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/lecfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/lecfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/lecfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/lecfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/lecfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/lecfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/lecfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/lecfp4-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/hashap-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/hashap-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/hashap-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/hashap-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/hashap-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/hashap-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/hashap-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/hashap-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/hashap-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/hashap-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/rdk5-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/rdk5-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/rdk5-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/rdk5-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/rdk5-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/rdk5-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/rdk5-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/rdk5-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/rdk5-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/rdk5-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/rdkDes-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/rdkDes-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/rdkDes-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/rdkDes-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/rdkDes-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/rdkDes-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/rdkDes-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/rdkDes-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/rdkDes-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/rdkDes-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-3A4_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/rdk7-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/rdk7-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/rdk7-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/rdk7-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/rdk7-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/rdk7-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/rdk7-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/rdk7-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/rdk7-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/rdk7-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/lfcfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/lfcfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/lfcfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/lfcfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/lfcfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/lfcfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/lfcfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/lfcfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/lfcfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/lfcfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/fcfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/fcfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/fcfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/fcfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/fcfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/fcfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/fcfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/fcfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/fcfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/fcfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/ecfp0-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/ecfp0-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/ecfp0-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/ecfp0-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/ecfp0-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/ecfp0-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/ecfp0-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/ecfp0-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/ecfp0-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/ecfp0-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/fcfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/fcfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/fcfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/fcfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/fcfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/fcfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/fcfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/fcfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/fcfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/fcfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/rdk6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/rdk6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/rdk6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/rdk6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/rdk6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/rdk6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/rdk6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/rdk6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/rdk6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/rdk6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/avalon-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/avalon-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/avalon-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/avalon-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/avalon-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/avalon-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/avalon-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/avalon-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/avalon-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/avalon-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/fcfp2-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/fcfp2-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/fcfp2-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/fcfp2-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/fcfp2-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/fcfp2-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/fcfp2-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/fcfp2-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/fcfp2-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/fcfp2-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/ecfp2-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/ecfp2-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/ecfp2-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/ecfp2-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/ecfp2-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/ecfp2-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/ecfp2-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/ecfp2-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/ecfp2-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/ecfp2-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/maccs-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/maccs-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/maccs-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/maccs-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/maccs-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/maccs-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/maccs-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/maccs-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/maccs-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/maccs-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/laval-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/laval-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/laval-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/laval-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/laval-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/laval-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/laval-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/laval-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/laval-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/laval-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/ecfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/ecfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/ecfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/ecfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/ecfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/ecfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/ecfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/ecfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/ecfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/ecfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/ecfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/ecfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/ecfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/ecfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/ecfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/ecfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/ecfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/ecfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/ecfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/ecfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/lfcfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/lfcfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/lfcfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/lfcfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/lfcfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/lfcfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/lfcfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/lfcfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/lfcfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/lfcfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/hashtt-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/hashtt-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/hashtt-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/hashtt-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/hashtt-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/hashtt-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/hashtt-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/hashtt-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/hashtt-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/hashtt-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/lecfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/lecfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/lecfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/lecfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/lecfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/lecfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/lecfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/lecfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/lecfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/lecfp6-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/lecfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/lecfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/lecfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/lecfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/lecfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/lecfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/lecfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/lecfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/lecfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/lecfp4-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/hashap-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/hashap-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/hashap-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/hashap-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/hashap-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/hashap-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/hashap-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/hashap-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/hashap-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/hashap-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/rdk5-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/rdk5-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/rdk5-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/rdk5-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/rdk5-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/rdk5-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/rdk5-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/rdk5-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/rdk5-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/rdk5-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/rdkDes-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/rdkDes-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/rdkDes-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/rdkDes-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/rdkDes-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/rdkDes-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/rdkDes-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/rdkDes-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/rdkDes-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/rdkDes-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/ecfp6_rdkDes_avalon_hashap-2C19_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/rdk7-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/rdk7-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/rdk7-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/rdk7-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/rdk7-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/rdk7-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/rdk7-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/rdk7-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/rdk7-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/rdk7-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/lfcfp6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/lfcfp6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/lfcfp6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/lfcfp6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/lfcfp6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/lfcfp6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/lfcfp6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/lfcfp6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/lfcfp6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/lfcfp6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/fcfp6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/fcfp6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/fcfp6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/fcfp6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/fcfp6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/fcfp6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/fcfp6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/fcfp6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/fcfp6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/fcfp6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/ecfp0-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/ecfp0-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/ecfp0-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/ecfp0-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/ecfp0-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/ecfp0-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/ecfp0-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/ecfp0-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/ecfp0-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/ecfp0-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/fcfp4-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/fcfp4-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/fcfp4-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/fcfp4-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/fcfp4-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/fcfp4-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/fcfp4-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/fcfp4-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/fcfp4-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/fcfp4-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/rdk6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/rdk6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/rdk6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/rdk6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/rdk6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/rdk6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/rdk6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/rdk6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/rdk6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/rdk6-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/avalon-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/avalon-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/avalon-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/avalon-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/avalon-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/avalon-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/avalon-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/avalon-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/avalon-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/avalon-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py RandomForestClassifier ../dataset/numpy_files/fcfp2-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py MLPClassifier ../dataset/numpy_files/fcfp2-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LogisticRegression ../dataset/numpy_files/fcfp2-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py XGBClassifier ../dataset/numpy_files/fcfp2-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py BaggingClassifier ../dataset/numpy_files/fcfp2-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py ExtraTreesClassifier ../dataset/numpy_files/fcfp2-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py LinearSVC ../dataset/numpy_files/fcfp2-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py Perceptron ../dataset/numpy_files/fcfp2-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py SGDClassifier ../dataset/numpy_files/fcfp2-2C9_inh.npy ../results_1 0.0 0.20 default
python3 model_dev_v5.py OneVsRestClassifier ../dataset/numpy_files/fcfp2-2C9_inh.npy ../results_1 0.0 0.20 default
